spring.application.name=contractmanagement

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=contractdb

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=contracts

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
# Display request duration in Swagger UI
springdoc.swagger-ui.display-request-duration=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

cors.allowed-origins=http://localhost:3000,http://localhost:3001