spring.application.name=contractmanagement

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=contractdb

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=contracts